In [5]:
import pandas as pd

# List of file names to load
file_names = [
    "paris_weekends.csv",
    "vienna_weekdays.csv",
    "vienna_weekends.csv",
    "rome_weekdays.csv",
    "rome_weekends.csv"
]

# Initialize an empty list to store DataFrames
dataframes = []

# Loop through each file name and load it into a DataFrame
for file_name in file_names:
    try:
        df = pd.read_csv(file_name)
        dataframes.append(df)  # Add the DataFrame to the list
        print(f"Successfully loaded {file_name}")
    except Exception as e:
        print(f"Error loading {file_name}: {e}")

Successfully loaded paris_weekends.csv
Successfully loaded vienna_weekdays.csv
Successfully loaded vienna_weekends.csv
Successfully loaded rome_weekdays.csv
Successfully loaded rome_weekends.csv

In [8]:
# Display the first few rows of each DataFrame
for i, df in enumerate(dataframes):
    print(f"\n--- Data Preview for {file_names[i]} ---")
    display(df.head())  # Show the top rows of each DataFrame

--- Data Preview for paris_weekends.csv ---

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,...,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,city,day_type
0,0,536.396682,Entire home/apt,False,False,5.0,False,0,1,9.0,...,1.351201,0.212346,390.776775,19.001549,1030.738507,47.550371,2.35900,48.86800,Paris,weekends
1,1,290.101594,Private room,False,True,2.0,True,0,0,10.0,...,0.699821,0.193710,518.478270,25.211044,1218.658866,56.219575,2.35385,48.86282,Paris,weekends
2,2,445.754497,Entire home/apt,False,False,4.0,False,0,1,10.0,...,0.968982,0.294343,432.689942,21.039580,1069.894793,49.356741,2.36023,48.86375,Paris,weekends
3,3,211.343089,Private room,False,True,2.0,False,0,0,10.0,...,3.302319,0.234740,444.555284,21.616533,902.856370,41.650870,2.31714,48.87475,Paris,weekends
4,4,266.334234,Entire home/apt,False,False,2.0,True,0,0,9.0,...,1.402430,0.055052,1013.458689,49.279502,1348.063511,62.189313,2.33408,48.85384,Paris,weekends

--- Data Preview for vienna_weekdays.csv ---

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,...,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,city,day_type
0,0,250.566814,Entire home/apt,False,False,3.0,True,1,0,10.0,...,1.732893,0.212627,118.646831,8.496979,185.096720,4.424871,16.36500,48.22300,Vienna,weekdays
1,1,156.604259,Entire home/apt,False,False,3.0,False,0,0,10.0,...,4.807912,0.228253,80.145015,5.739643,85.727600,2.049380,16.33356,48.17459,Vienna,weekdays
2,2,283.056354,Entire home/apt,False,False,5.0,True,0,1,10.0,...,2.811773,0.244163,101.248112,7.250957,151.364288,3.618473,16.33600,48.21100,Vienna,weekdays
3,3,301.755370,Entire home/apt,False,False,4.0,True,0,1,10.0,...,3.240595,0.610430,92.473938,6.622588,129.863831,3.104489,16.33006,48.20921,Vienna,weekdays
4,4,150.760816,Entire home/apt,False,False,2.0,True,0,1,10.0,...,2.241146,1.119507,124.256767,8.898738,154.348971,3.689824,16.38867,48.19104,Vienna,weekdays

--- Data Preview for vienna_weekends.csv ---

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,...,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,city,day_type
0,0,324.661665,Entire home/apt,False,False,4.0,True,0,1,10.0,...,3.240613,0.610450,92.473467,6.622340,129.862880,3.138736,16.33006,48.20921,Vienna,weekends
1,1,150.760816,Entire home/apt,False,False,2.0,True,0,1,10.0,...,2.241126,1.119505,124.258002,8.898538,154.350322,3.730588,16.38867,48.19104,Vienna,weekends
2,2,196.339668,Entire home/apt,False,False,3.0,True,0,1,9.0,...,2.371551,0.452419,125.413127,8.981261,206.642494,4.994469,16.34236,48.20436,Vienna,weekends
3,3,107.753079,Private room,False,True,2.0,False,0,0,8.0,...,3.629114,0.473164,62.459416,4.472931,93.810714,2.267369,16.37837,48.24102,Vienna,weekends
4,4,196.339668,Entire home/apt,False,False,4.0,True,0,1,9.0,...,2.395063,0.443635,124.020359,8.881520,202.318070,4.889950,16.34198,48.20456,Vienna,weekends

--- Data Preview for rome_weekdays.csv ---

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,...,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,city,day_type
0,0,156.874664,Private room,False,True,2.0,True,1,0,10.0,...,2.978468,1.595733,281.163932,6.230648,697.727246,15.191486,12.48654,41.92498,Rome,weekdays
1,1,172.772543,Private room,False,True,2.0,False,1,0,9.0,...,0.935371,0.649269,482.707193,10.696887,1251.524333,27.249208,12.49627,41.90801,Rome,weekdays
2,2,277.745307,Entire home/apt,False,False,4.0,False,0,1,9.0,...,2.203025,0.494697,691.708998,15.328408,1625.897266,35.400361,12.47700,41.90700,Rome,weekdays
3,3,444.906834,Entire home/apt,False,False,6.0,False,1,0,9.0,...,2.703010,1.295153,805.592641,17.852092,2035.819533,44.325522,12.46969,41.90019,Rome,weekdays
4,4,131.391298,Private room,False,True,3.0,False,1,0,9.0,...,1.295968,0.867455,317.076369,7.026475,836.622814,18.215634,12.51544,41.89463,Rome,weekdays

--- Data Preview for rome_weekends.csv ---

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,...,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,city,day_type
0,0,172.772543,Private room,False,True,2.0,False,0,0,10.0,...,1.222582,0.397760,550.078435,12.187232,1075.412107,23.430621,12.50181,41.88987,Rome,weekends
1,1,156.874664,Private room,False,True,2.0,True,1,0,10.0,...,2.978482,1.595742,281.162756,6.229285,697.725034,15.201736,12.48654,41.92498,Rome,weekends
2,2,195.917986,Private room,False,True,2.0,False,1,0,9.0,...,0.935379,0.649273,482.708059,10.694611,1251.514249,27.267459,12.49627,41.90801,Rome,weekends
3,3,298.552825,Entire home/apt,False,False,4.0,False,0,1,9.0,...,2.203023,0.494699,691.716421,15.325284,1625.911297,35.424663,12.47700,41.90700,Rome,weekends
4,4,131.391298,Private room,False,True,3.0,False,1,0,9.0,...,1.295984,0.867473,317.074092,7.024917,836.616071,18.227835,12.51544,41.89463,Rome,weekends

In [11]:
# Clean each DataFrame
for i, df in enumerate(dataframes):
    df.dropna(inplace=True)           # Remove rows with missing values
    df.drop_duplicates(inplace=True)   # Remove duplicate rows
    df.reset_index(drop=True, inplace=True)  # Reset the index
    print(f"Cleaned data for {file_names[i]}")

Cleaned data for paris_weekends.csv
Cleaned data for vienna_weekdays.csv
Cleaned data for vienna_weekends.csv
Cleaned data for rome_weekdays.csv
Cleaned data for rome_weekends.csv

In [20]:
# Combine all DataFrames into a single DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)
print("Combined all DataFrames into a single DataFrame.")

Combined all DataFrames into a single DataFrame.

In [22]:
combined_df

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,...,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,city,day_type
0,0,536.396682,Entire home/apt,False,False,5.0,False,0,1,9.0,...,1.351201,0.212346,390.776775,19.001549,1030.738507,47.550371,2.35900,48.86800,Paris,weekends
1,1,290.101594,Private room,False,True,2.0,True,0,0,10.0,...,0.699821,0.193710,518.478270,25.211044,1218.658866,56.219575,2.35385,48.86282,Paris,weekends
2,2,445.754497,Entire home/apt,False,False,4.0,False,0,1,10.0,...,0.968982,0.294343,432.689942,21.039580,1069.894793,49.356741,2.36023,48.86375,Paris,weekends
3,3,211.343089,Private room,False,True,2.0,False,0,0,10.0,...,3.302319,0.234740,444.555284,21.616533,902.856370,41.650870,2.31714,48.87475,Paris,weekends
4,4,266.334234,Entire home/apt,False,False,2.0,True,0,0,9.0,...,1.402430,0.055052,1013.458689,49.279502,1348.063511,62.189313,2.33408,48.85384,Paris,weekends
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16117,4530,413.812452,Entire home/apt,False,False,4.0,False,0,1,10.0,...,1.933569,0.270592,657.307139,14.562931,1408.407648,30.685786,12.48137,41.90860,Rome,weekends
16118,4531,582.376733,Entire home/apt,False,False,6.0,True,0,1,10.0,...,3.124166,1.939505,540.341368,11.971503,1985.435361,43.257820,12.46700,41.89100,Rome,weekends
16119,4532,878.591635,Entire home/apt,False,False,6.0,True,1,0,10.0,...,2.759242,1.195339,759.369097,16.824159,1783.268631,38.853097,12.46900,41.90100,Rome,weekends
16120,4533,447.244757,Entire home/apt,False,False,4.0,True,1,0,10.0,...,1.641598,0.858837,1125.857244,24.943866,1687.895816,36.775155,12.48342,41.89634,Rome,weekends
16121,4534,265.821897,Entire home/apt,False,False,6.0,False,0,1,10.0,...,4.411877,0.352493,167.701907,3.715510,467.340278,10.182211,12.53000,41.86700,Rome,weekends

In [25]:
# Save the combined DataFrame to a new CSV file
combined_df.to_csv("combined_cleaned_data.csv", index=False)
print("Saved combined_cleaned_data.csv locally.")

Saved combined_cleaned_data.csv locally.

# List of file names to load and update

In [29]:
import pandas as pd

# List of file names to load and update
file_names = [
    "paris_weekends.csv",
    "vienna_weekdays.csv",
    "vienna_weekends.csv",
    "rome_weekdays.csv",
    "rome_weekends.csv"
]

# Loop through each file name
for file_name in file_names:
    try:
        # Load the CSV file
        df = pd.read_csv(file_name)
        
        # Extract city and day type from the file name
        city = file_name.split('_')[0].capitalize()  # Get city name and capitalize it
        day_type = file_name.split('_')[1].split('.')[0]  # Get day type (weekday or weekend)
        
        # Add new columns for city and day type
        df['city'] = city
        df['day_type'] = day_type
        
        # Save the updated DataFrame back to the same file
        df.to_csv(file_name, index=False)
        print(f"Updated and saved {file_name} with new columns.")
        
    except Exception as e:
        print(f"Error updating {file_name}: {e}")

Updated and saved paris_weekends.csv with new columns.
Updated and saved vienna_weekdays.csv with new columns.
Updated and saved vienna_weekends.csv with new columns.
Updated and saved rome_weekdays.csv with new columns.
Updated and saved rome_weekends.csv with new columns.

#  ---

In [34]:
!pip install sqlalchemy pymysql mysql-connector-python

Requirement already satisfied: sqlalchemy in c:\users\pravin\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: pymysql in c:\users\pravin\anaconda3\lib\site-packages (1.1.1)
Requirement already satisfied: mysql-connector-python in c:\users\pravin\anaconda3\lib\site-packages (9.1.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\pravin\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\pravin\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [35]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\pravin\anaconda3\lib\site-packages (9.1.0)

In [36]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\pravin\anaconda3\lib\site-packages (1.1.1)

In [37]:
!pip install sqlalchemy
!pip install mysqlclient
!pip install mysql-connector-python
!pip install pymysql

Requirement already satisfied: sqlalchemy in c:\users\pravin\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\pravin\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\pravin\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: mysqlclient in c:\users\pravin\anaconda3\lib\site-packages (2.2.6)
Requirement already satisfied: mysql-connector-python in c:\users\pravin\anaconda3\lib\site-packages (9.1.0)
Requirement already satisfied: pymysql in c:\users\pravin\anaconda3\lib\site-packages (1.1.1)

In [42]:
import warnings
warnings.filterwarnings('ignore')
from sqlalchemy import create_engine
import pandas as pd

# Database connection details
DATABASE_TYPE = 'mysql' 
DBAPI = 'mysqldb'  # Use 'mysqlconnector' instead of 'mysqldb'
USER = 'root' 
PASSWORD = "pravinSTR%402129" 
HOST = '127.0.0.1' 
PORT = '3306' 
DATABASE = 'Neural_Nebula_040' 

# Create the engine string
engine_string = f"{DATABASE_TYPE}+{DBAPI}://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"

# Create SQLAlchemy engine
engine = create_engine(engine_string)

# Connect to the database
conn = engine.connect()

# Assuming PerformanceRating is a DataFrame, you can save it to SQL
combined_df.to_sql('combined_df', con=engine, index=False, if_exists='replace')

16122